[workspace]
[package]
name = "buggy"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_template_abi = { path = "../../../../template_abi", default-features = false, features = ["alloc"] }
lol_alloc = "0.4.0"

[lib]
crate-type = ["cdylib"]

[features]
no_template_def = []
unexpected_export_function = []
engine_call_in_alloc = []
engine_call_in_free = []
engine_call_in_response_alloc = []
