// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestrictedAccessRule } from "./RestrictedAccessRule";

export type AccessRule = "AllowAll" | "DenyAll" | { Restricted: RestrictedAccessRule };
