// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "./ResourceAddress";
import type { ResourceType } from "./ResourceType";
import type { SubstateId } from "./SubstateId";

export interface BalanceEntry {
  vault_address: SubstateId;
  resource_address: ResourceAddress;
  balance: number;
  resource_type: ResourceType;
  confidential_balance: number;
  token_symbol: string | null;
}
