// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { ExtraData } from "./ExtraData";
import type { NodeHeight } from "./NodeHeight";
import type { RistrettoPublicKeyBytes } from "./RistrettoPublicKeyBytes";
import type { SchnorrSignatureBytes } from "./SchnorrSignatureBytes";
import type { ShardGroup } from "./ShardGroup";
import type { ShardGroupAccumulatedData } from "./ShardGroupAccumulatedData";

export type BlockHeader = {
  /**
   * "Cached" block ID/hash. This is computed from the contents of the block header.
   */
  id: string;
  /**
   * Network this block belongs to.
   */
  network: string;
  /**
   * Parent block ID.
   */
  parent: string;
  /**
   * The quorum certificate proposed in this block. Note that this QC justifies a previous block.
   */
  justify_id: string;
  /**
   * Block height.
   */
  height: NodeHeight;
  /**
   * Epoch this block belongs to.
   */
  epoch: Epoch;
  /**
   * Shard group that created this block.
   */
  shard_group: ShardGroup;
  /**
   * The public key of the proposer.
   */
  proposed_by: RistrettoPublicKeyBytes;
  /**
   * The total leader fee for this block. This should match the sum of the leader fees in the block's body.
   */
  total_leader_fee: bigint;
  /**
   * A Merkle root hash committing to all state after this block has been applied.
   */
  state_merkle_root: string;
  /**
   * A Merkle root hash committing to commands in this block. It is zero if the block has no commands.
   */
  command_merkle_root: string;
  /**
   * Proposer signature that signs the Block ID
   */
  signature: SchnorrSignatureBytes | null;
  /**
   * The Unix Epoch timestamp indicating the creation time of the block. Currently, this can be chosen arbitrarily
   * and is only informational/used for metrics.
   */
  timestamp: bigint;
  /**
   * The epoch hash is a hash given by the epoch oracle. E.g. the base layer epoch oracle gives the first block hash
   * of the epoch.
   */
  epoch_hash: string;
  /**
   * Accumulated data for the shard group up to and including this block.
   */
  accumulated_data: ShardGroupAccumulatedData;
  /**
   * Extra data to allow for potential future data to be provided as necessary without breaking changes.
   * Currently, this is used to store the block's sidechain_id (if applicable).
   */
  extra_data: ExtraData;
  /**
   * The protocol version this block was produced under, resolved from the network's activation schedule at
   * [`Self::epoch`]. It makes the block self-describing: [`Self::calculate_hash`] and the L1 verifier in
   * `tari_sidechain` both select the hash schema from this field rather than from the schedule.
   *
   * A header that carries no version is under [`ProtocolVersion::V0`], so blocks written before the field
   * existed decode and hash unchanged.
   */
  protocol_version: number;
};
