// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface ClaimBurnRequest {
  account: ComponentAddressOrName | null;
  claim_proof: string;
  max_fee: number | null;
  key_id: number | null;
}
