// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignProposal } from "./ForeignProposal";
import type { TransactionAtom } from "./TransactionAtom";

export type Command =
  | { Prepare: TransactionAtom }
  | { LocalPrepared: TransactionAtom }
  | { Accept: TransactionAtom }
  | { ForeignProposal: ForeignProposal };
