// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Committee } from "./Committee";
import type { SubstateAddress } from "./SubstateAddress";

export interface CommitteeShardInfo<TAddr> { shard: number, substate_address_range: { start: SubstateAddress, end: SubstateAddress, }, validators: Committee<TAddr>, }