// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";

export interface CommitteeShard {
  num_committees: number;
  num_members: number;
  shard: Shard;
}
