// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumPreshards } from "./NumPreshards";
import type { ShardGroup } from "./ShardGroup";

export interface CommitteeInfo {
  num_shards: NumPreshards;
  num_shard_group_members: number;
  num_committees: number;
  shard_group: ShardGroup;
}
