// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutputStatement } from "./ConfidentialOutputStatement";

export interface ConfidentialWithdrawProof {
  inputs: Array<Uint8Array>;
  input_revealed_amount: number;
  output_proof: ConfidentialOutputStatement;
  balance_proof: Array<number>;
}
