// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ConfidentialOutput {
  commitment: string;
  stealth_public_nonce: string;
  encrypted_data: Array<number>;
  minimum_value_promise: number;
}
