// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { ResourceAddress } from "./ResourceAddress";

export interface ConfidentialTransferRequest {
  account: ComponentAddressOrName | null;
  amount: number;
  resource_address: ResourceAddress;
  destination_public_key: string;
  max_fee: number | null;
  dry_run: boolean;
}
