// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { ConfidentialStatement } from "./ConfidentialStatement";

export interface ConfidentialOutputProof {
  output_statement: ConfidentialStatement | null;
  change_statement: ConfidentialStatement | null;
  range_proof: Array<number>;
  output_revealed_amount: Amount;
  change_revealed_amount: Amount;
}
