// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialStatement } from "./ConfidentialStatement";

export interface ConfidentialOutputProof {
  output_statement: ConfidentialStatement;
  change_statement: ConfidentialStatement | null;
  range_proof: Array<number>;
}
