// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutputProof } from "./ConfidentialOutputProof";

export interface ConfidentialWithdrawProof {
  inputs: Array<number>;
  input_revealed_amount: number;
  output_proof: ConfidentialOutputProof;
  balance_proof: Array<number>;
}
