// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ConfidentialStatement {
  commitment: Array<number>;
  sender_public_nonce: Array<number>;
  encrypted_data: Array<number>;
  minimum_value_promise: number;
}
