// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedData } from "./EncryptedData";

export interface ConfidentialOutput {
  commitment: string;
  stealth_public_nonce: string;
  encrypted_data: EncryptedData;
  minimum_value_promise: bigint;
}
