// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardEvidence } from "./ShardEvidence";
import type { SubstateAddress } from "./SubstateAddress";

export interface Evidence { evidence: Record<SubstateAddress, ShardEvidence>, }