// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeReceipt } from "./FeeReceipt";
import type { FinalizeResult } from "./FinalizeResult";

export interface ExecuteResult {
  finalize: FinalizeResult;
  fee_receipt: FeeReceipt | null;
}
