// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { ExecuteResult } from "./ExecuteResult";
import type { SubstateAddress } from "./SubstateAddress";
import type { Transaction } from "./Transaction";

export interface ExecutedTransaction {
  transaction: Transaction;
  result: ExecuteResult;
  resulting_outputs: Array<SubstateAddress>;
  execution_time: { secs: number; nanos: number };
  final_decision: Decision | null;
  finalized_time: { secs: number; nanos: number } | null;
  abort_details: string | null;
}
