// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeSource } from "./FeeSource";

export interface FeeBreakdown {
  breakdown: Record<FeeSource, bigint>;
}
