// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FeeCostBreakdown {
  total_fees_charged: number;
  breakdown: Array<[FeeSource, number]>;
}
