// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FeeClaim {
  epoch: number;
  validator_public_key: string;
  amount: number;
}
