// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";

export interface FeeClaim {
  epoch: bigint;
  validator_public_key: string;
  amount: Amount;
}
