// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { FeeSource } from "./FeeSource";

export interface FeeReceipt {
  total_fee_payment: number;
  total_fees_paid: number;
  cost_breakdown: Array<[FeeSource, number]>;
}
