// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { ForeignProposalState } from "./ForeignProposalState";
import type { NodeHeight } from "./NodeHeight";
import type { Shard } from "./Shard";

export interface ForeignProposal {
  bucket: Shard;
  block_id: BlockId;
  state: ForeignProposalState;
  proposed_height: NodeHeight | null;
}
