// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForeignProposalState } from "./ForeignProposalState";
import type { NodeHeight } from "./NodeHeight";

export interface ForeignProposal { bucket: number, block_id: string, state: ForeignProposalState, proposed_height: NodeHeight | null, transactions: Array<string>, base_layer_block_height: bigint, }