// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseLayerValidatorNode } from "./BaseLayerValidatorNode";

export interface GetAllVnsResponse {
  vns: Array<BaseLayerValidatorNode>;
}
