// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ordering } from "./Ordering";

export interface GetBlocksRequest {
  limit: number;
  offset: number;
  ordering: Ordering | null;
}
