// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerTransactionFinalizedResult } from "./IndexerTransactionFinalizedResult";

export interface GetRelatedTransactionsResponse {
  transaction_results: Array<IndexerTransactionFinalizedResult>;
}
