// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexedWellKnownTypes } from "./IndexedWellKnownTypes";

export interface IndexedValue {
  indexed: IndexedWellKnownTypes;
  value: any;
}
