// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexedValue } from "./IndexedValue";
import type { Type } from "./Type";

export interface InstructionResult { indexed: IndexedValue, return_type: Type, }