// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NonFungibleId = { U256: Array<number> } | { String: string } | { Uint32: number } | { Uint64: number };
