// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceAddress } from "./ResourceAddress";

export interface NonFungibleIndexAddress { resource_address: ResourceAddress, index: number, }