// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleAddress } from "./NonFungibleAddress";

export interface NonFungibleIndex {
  referenced_address: NonFungibleAddress;
}
