// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumPreshards = "P1" | "P2" | "P4" | "P8" | "P16" | "P32" | "P64" | "P128" | "P256";