// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumPreshards =
  | "One"
  | "Two"
  | "Four"
  | "Eight"
  | "Sixteen"
  | "ThirtyTwo"
  | "SixtyFour"
  | "OneTwentyEight"
  | "TwoFiftySix";
