// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";
import type { ResourceAddress } from "./ResourceAddress";

export interface ProofsGenerateRequest {
  amount: number;
  reveal_amount: number;
  account: ComponentAddressOrName | null;
  resource_address: ResourceAddress;
  destination_public_key: string;
}
