// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { Epoch } from "./Epoch";
import type { NodeHeight } from "./NodeHeight";
import type { QcId } from "./QcId";
import type { QuorumDecision } from "./QuorumDecision";
import type { ValidatorSignature } from "./ValidatorSignature";

export interface QuorumCertificate {
  qc_id: QcId;
  block_id: BlockId;
  block_height: NodeHeight;
  epoch: Epoch;
  signatures: Array<ValidatorSignature>;
  merged_proof: any;
  leaf_hashes: Array<string>;
  decision: QuorumDecision;
}
