// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RejectReason =
  | { ShardsNotPledged: string }
  | { ExecutionFailure: string }
  | "PreviousQcRejection"
  | { ShardPledgedToAnotherPayload: string }
  | { ShardRejected: string }
  | "FeeTransactionFailed"
  | { FeesNotPaid: string };
