// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRule } from "./AccessRule";
import type { UpdateRule } from "./UpdateRule";

/**
 * Information needed to specify access rules to a resource
 */
export type ResourceAccessRules = {
  mint: AccessRule;
  mint_updater: UpdateRule;
  burn: AccessRule;
  burn_updater: UpdateRule;
  recall: AccessRule;
  recall_updater: UpdateRule;
  withdraw: AccessRule;
  withdraw_updater: UpdateRule;
  deposit: AccessRule;
  deposit_updater: UpdateRule;
  update_nft_data: AccessRule;
  nft_data_updater: UpdateRule;
  freeze: AccessRule;
  freeze_updater: UpdateRule;
  update_metadata: AccessRule;
  metadata_updater: UpdateRule;
  /**
   * Who may install, replace or remove the resource's [`AuthHook`](crate::AuthHook). The hook itself is not
   * an [`AccessRule`], so this updater stands alone rather than pairing with one.
   *
   * A hook runs on nearly every resource action, so one that panics or denies unconditionally takes the
   * resource offline and strands the balances in its vaults. `Locked` — the default — keeps a hook binding
   * for the life of the resource; anything else lets the hook be repaired or retired, at the cost of letting
   * whoever satisfies the updater change the rules that existing holders are relying on — up to and
   * including giving a hook-free resource a hook.
   */
  auth_hook_updater: UpdateRule;
};
