// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeResult } from "./FinalizeResult";

export interface RevealFundsResponse {
  transaction_id: string;
  fee: number;
  result: FinalizeResult;
}
