// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { Hash } from "./Hash";
import type { NonFungibleAddress } from "./NonFungibleAddress";
import type { ResourceAddress } from "./ResourceAddress";

export type RuleRequirement =
  | { Resource: ResourceAddress }
  | { NonFungibleAddress: NonFungibleAddress }
  | { ScopedToComponent: ComponentAddress }
  | { ScopedToTemplate: Hash };
