// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateLockType } from "./SubstateLockType";

export interface ShardEvidence { qc_ids: Array<string>, lock: SubstateLockType, }