// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shard } from "./Shard";

export interface ShardGroup { start: Shard, end_inclusive: Shard, }