// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LockFlag } from "./LockFlag";
import type { QcId } from "./QcId";

export interface ShardEvidence {
  qc_ids: Array<QcId>;
  lock: LockFlag;
}
