// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DryRunTransactionFinalizeResult } from "./DryRunTransactionFinalizeResult";
import type { TransactionId } from "./TransactionId";

export interface SubmitTransactionResponse {
  transaction_id: TransactionId;
  dry_run_result: DryRunTransactionFinalizeResult | null;
}
