// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Substate } from "./Substate";
import type { SubstateId } from "./SubstateId";

export interface SubstateDiff { up_substates: Array<[SubstateId, Substate]>, down_substates: Array<[SubstateId, number]>, }