// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateLockType } from "./SubstateLockType";
import type { SubstateRequirement } from "./SubstateRequirement";

export interface SubstateRequirementLockIntent { substate_requirement: SubstateRequirement, version_to_lock: number, lock_type: SubstateLockType, }