// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";

export interface SubstateDestroyed {
  by_transaction: string;
  justify: string;
  by_block: string;
  at_epoch: Epoch;
}
