// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { NodeHeight } from "./NodeHeight";
import type { SubstateDestroyed } from "./SubstateDestroyed";
import type { SubstateId } from "./SubstateId";
import type { SubstateValue } from "./SubstateValue";

export interface SubstateRecord { substate_id: SubstateId, version: number, substate_value: SubstateValue, state_hash: string, created_by_transaction: string, created_justify: string, created_block: string, created_height: NodeHeight, created_at_epoch: Epoch, destroyed: SubstateDestroyed | null, }