// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateDefV1 } from "./TemplateDefV1";

export type TemplateDef = { V1: TemplateDefV1 };
