// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplateRegistrationRequest {
  template_name: string;
  template_version: number;
  repo_url: string;
  commit_hash: Array<number>;
  binary_sha: Array<number>;
  binary_url: string;
  template_type: string;
}
