// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDef } from "./FunctionDef";

export interface TemplateDefV1 {
  template_name: string;
  tari_version: string;
  functions: Array<FunctionDef>;
}
