// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "./ExecuteResult";
import type { SubstateRequirement } from "./SubstateRequirement";
import type { TransactionId } from "./TransactionId";

export interface TransactionSubmitResponse {
  transaction_id: TransactionId;
  inputs: Array<SubstateRequirement>;
  result: ExecuteResult | null;
  json_result: Array<any> | null;
}
