/*
 * //  Copyright 2024 The Tari Project
 * //  SPDX-License-Identifier: BSD-3-Clause
 */

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionStatus =
  | "New"
  | "DryRun"
  | "Pending"
  | "Accepted"
  | "Rejected"
  | "InvalidTransaction"
  | "OnlyFeeAccepted";
