// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionId } from "./TransactionId";

export interface TransactionWaitResultRequest {
  transaction_id: TransactionId;
  timeout_secs: bigint | null;
}
