// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateAddress } from "./SubstateAddress";
import type { TransactionId } from "./TransactionId";

export interface TransactionClaimBurnResponse {
  transaction_id: TransactionId;
  inputs: Array<SubstateAddress>;
  outputs: Array<SubstateAddress>;
}
