// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { Evidence } from "./Evidence";
import type { LeaderFee } from "./LeaderFee";
import type { TransactionPoolStage } from "./TransactionPoolStage";

export interface TransactionPoolRecord { transaction_id: string, evidence: Evidence, remote_evidence: Evidence | null, transaction_fee: number, leader_fee: LeaderFee | null, stage: TransactionPoolStage, pending_stage: TransactionPoolStage | null, original_decision: Decision, local_decision: Decision | null, remote_decision: Decision | null, is_ready: boolean, }