// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { Evidence } from "./Evidence";
import type { TransactionId } from "./TransactionId";

export interface TransactionAtom {
  id: TransactionId;
  decision: Decision;
  evidence: Evidence;
  transaction_fee: bigint;
  leader_fee: bigint;
}
