// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { TransactionAtom } from "./TransactionAtom";
import type { TransactionPoolStage } from "./TransactionPoolStage";

export interface TransactionPoolRecord {
  atom: TransactionAtom;
  stage: TransactionPoolStage;
  pending_stage: TransactionPoolStage | null;
  local_decision: Decision | null;
  remote_decision: Decision | null;
  is_ready: boolean;
}
