// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UnclaimedConfidentialOutput { commitment: string, encrypted_data: Array<number>, }