// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedData } from "./EncryptedData";

export interface UnclaimedConfidentialOutput {
  commitment: string;
  encrypted_data: EncryptedData;
}
