// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { Instruction } from "./Instruction";
import type { SubstateAddress } from "./SubstateAddress";

export interface UnsignedTransaction {
  fee_instructions: Array<Instruction>;
  instructions: Array<Instruction>;
  inputs: Array<SubstateAddress>;
  input_refs: Array<SubstateAddress>;
  filled_inputs: Array<SubstateAddress>;
  min_epoch: Epoch | null;
  max_epoch: Epoch | null;
}
