// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { Epoch } from "./Epoch";

export interface ValidatorFee {
  validator_public_key: string;
  epoch: Epoch;
  block_id: BlockId;
  total_fee_due: bigint;
  total_transaction_fee: bigint;
}
