// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValidatorSignature { public_key: string, signature: {public_nonce : string, signature: string}, }