// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceContainer } from "./ResourceContainer";

export interface Vault { resource_container: ResourceContainer, }