// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceContainer } from "./ResourceContainer";
import type { VaultId } from "./VaultId";

export interface Vault {
  vault_id: VaultId;
  resource_container: ResourceContainer;
}
