// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateId } from "./SubstateId";

export interface VersionedSubstateId { substate_id: SubstateId, version: number, }