// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateLockFlag } from "./SubstateLockFlag";
import type { VersionedSubstateId } from "./VersionedSubstateId";

export interface VersionedSubstateIdLockIntent {
  versioned_substate_id: VersionedSubstateId;
  lock_flag: SubstateLockFlag;
}
