[package]
name = "tari_template_macros"
version = "0.50.0-pre.0"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Tari template macro"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.42"
# Locked due to https://github.com/diesel-rs/diesel/issues/3541
quote = "=1.0.20"
syn = { version = "1.0.98", features = ["full", "extra-traits"] }

[dev-dependencies]
indoc = "1.0.6"