[package]
name = "tari_template_macros"
version = "0.1.0"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Tari template macro"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
tari_template_abi = { version="0.1.0", path = "../template_abi" }
tari_bor = { version="0.1.0", path = "../tari_bor" }

proc-macro2 = "1.0.56"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[dev-dependencies]
indoc = "1.0.6"
