[package]
name = "tari_transaction"
version = "0.50.0-pre.0"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Tari transaction builder and associated data types"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", tag = "v0.51.0-pre.4" }
tari_engine_types = { path = "../engine_types" }
tari_dan_common_types = { path = "../common_types" }
tari_crypto = { version = "0.17", features = ["borsh"] }
tari_template_lib = { path = "../template_lib" }

serde = "1.0.126"
thiserror = "1"

#siphasher = "0.3.1"
#rand = "*"
#bincode = "1.3.3"