// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "../Block";

export type GetBlockResponse = {
  block: Block;
  /**
   * Total WASM metering points consumed by transactions executed for this block.
   */
  total_wasm_execution_points: bigint;
  /**
   * Total native verification points charged to transactions executed for this block.
   */
  total_native_execution_points: bigint;
  /**
   * The per-block execution points budget a leader packs against. It governs the sum of the two totals above,
   * so only that sum is a meaningful proportion of it.
   */
  max_block_execution_points: bigint;
  /**
   * Total execution weight of the block's transaction commands: each transaction's weight discounted by how much
   * of the work its command stage adds. Foreign proposal commands carry no execution weight and so
   * contribute nothing.
   */
  total_block_execution_weight: bigint;
  /**
   * The execution weight a block may carry and still be voted for. Weight stands in for the size, IO and storage
   * cost that metering does not see, so for ordinary traffic this budget fills long before the execution points
   * one.
   */
  max_block_validation_weight: bigint;
};
