// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "..\\Epoch";
import type { SubstateAddress } from "..\\SubstateAddress";

export interface GetCommitteeRequest { epoch: Epoch, substate_address: SubstateAddress, }