// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Committee } from "../Committee";
import type { PeerAddress } from "../PeerAddress";

export interface GetCommitteeResponse { committee: Committee<PeerAddress>, }