// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitteeInfo } from "../CommitteeInfo";
import type { Epoch } from "../Epoch";

export interface GetEpochManagerStatsResponse {
  current_epoch: Epoch;
  current_block_height: number;
  current_block_hash: string;
  is_valid: boolean;
  committee_info: CommitteeInfo | null;
}
