// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionPoolRecord } from "../TransactionPoolRecord";

export interface GetTxPoolResponse { tx_pool: Array<TransactionPoolRecord>, }