// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "../Transaction";

export interface SubmitTransactionRequest {
  transaction: Transaction;
  is_dry_run: boolean;
}
