// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplateRegistrationResponse { template_address: Array<number>, transaction_id: number, }