// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDef } from "./FunctionDef";

export interface TemplateAbi {
  template_name: string;
  functions: Array<FunctionDef>;
  version: string;
}
