// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VNFunctionDef } from "./VNFunctionDef";

export interface TemplateAbi { template_name: string, functions: Array<VNFunctionDef>, version: string, }