// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplateMetadata {
  name: string;
  address: Uint8Array;
  url: string;
  binary_sha: Array<number>;
  height: number;
}
