// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "../Epoch";

export interface ValidatorFee { validator_public_key: string, epoch: Epoch, block_id: string, total_fee_due: number, total_transaction_fee: number, }