// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface VNAddPeerRequest {
  public_key: string;
  addresses: Array<string>;
  wait_for_dial: boolean;
}
