// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VNArgDef } from "./VNArgDef";

export interface VNFunctionDef { name: string, arguments: Array<VNArgDef>, output: string, is_mut: boolean, }