// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VNConnection } from "./VNConnection";

export interface VNGetConnectionsResponse {
  connections: Array<VNConnection>;
}
