// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "..\\Epoch";

export interface VNGetValidatorFeesRequest {
  epoch_range: { start: Epoch; end: Epoch };
  validator_public_key: string;
}
