[package]
name = "tari_transaction_manifest"
version = "0.50.0-pre.0"
edition = "2021"

[dependencies]
tari_template_lib = { path = "../template_lib" }
tari_engine_types = { path = "../engine_types" }
tari_template_builtin = { path = "../template_builtin" }

proc-macro2 = "1.0.42"
syn = { version = "1.0.98", features = ["full", "extra-traits"] }
thiserror = "1.0"
