[package]
name = "tari_transaction_manifest"
version = "0.0.3"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Tari transaction manifest"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

[dependencies]
tari_template_lib = { path = "../template_lib" }
tari_engine_types = { path = "../engine_types" }
tari_template_builtin = { path = "../template_builtin" }
tari_bor = { path = "../tari_bor" }

proc-macro2 = "1.0.42"
syn = { version = "1.0.98", features = ["full", "extra-traits"] }
thiserror = "1.0"
