[package]
name = "tari_transaction_manifest"
version = "0.35.1"
edition = "2021"

[dependencies]
tari_template_lib = { path = "../template_lib" }
tari_engine_types = { path = "../engine_types" }

proc-macro2 = "1.0.42"
quote = "1.0.20"
syn = { version = "1.0.98", features = ["full", "extra-traits"] }
thiserror = "1.0"
