[package]
name = "consensus_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tari_dan_common_types = { path = "../common_types" }
tari_consensus = { path = "../consensus" }
tari_dan_storage = { path = "../storage" }
tari_state_store_sqlite = { path = "../state_store_sqlite" }
tari_transaction = { path = "../transaction" }
tari_engine_types = { path = "../engine_types" }
tari_epoch_manager = { path = "../epoch_manager" }

tari_common_types = { git = "https://github.com/tari-project/tari.git", tag = "v0.51.0-pre.4" }
tari_mmr = { git = "https://github.com/tari-project/tari.git", tag = "v0.51.0-pre.4" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", tag = "v0.51.0-pre.4" }
tari_crypto = "0.17"

anyhow = "1.0"
async-trait = "0.1.68"
log = "0.4"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1", default-features = false, features = ["sync", "rt-multi-thread"] }
rand = "0.7"
futures = "0.3"
env_logger = "0.10.0"
itertools = "0.11.0"
