{
 "title": "VN1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consensus: Finality rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tari_consensus_transaction_finalized_committed[$__rate_interval]) + rate(tari_consensus_transaction_finalized_aborted[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Commands per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (public_key) (tari_consensus_num_commands)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Pool size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tari_consensus_transactions_pool_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool: Avg Execution time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tari_mempool_transactions_execute_time_sum / tari_mempool_transactions_execute_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Transactions Aborted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "tari_consensus_transaction_finalized_aborted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Transaction Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(tari_consensus_transaction_ready_for_consensus[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Transactions Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tari_consensus_transaction_finalized_committed{public_key=\"c6886d1ec5302aa5f9bcadffad3f9e1cbbd7c8b5637253fb12f2a7e4cb331372\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool: Transactions Rx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(tari_mempool_transactions_received[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: commands per block histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cmds" } },
   "targets": [
    { "expr": "tari_consensus_num_commands", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consensus: Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(tari_consensus_messages_received{public_key=\"c6886d1ec5302aa5f9bcadffad3f9e1cbbd7c8b5637253fb12f2a7e4cb331372\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "rate(tari_consensus_errors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus: Leader failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "rate(tari_consensus_leader_failures[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}