[package]
name = "libp2p-substream"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53.1", features = ["identify"]  }

# smallvec 2.0.0 is not Send, so we use 1.11.2
smallvec = "1.11.2"
tracing = "0.1.40"