// Copyright 2024. The Tari Project
// SPDX-License-Identifier: BSD-3-Clause

// This file was generated by cargo-bindgen. Please do not edit manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void initialize_wallet_sdk(int *error_out);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
