// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddress } from "./ComponentAddress";
import type { ResourceAddress } from "./ResourceAddress";
import type { SubstateId } from "./SubstateId";

export type JrpcPermission = "AccountInfo" | { "NftGetOwnershipProof": ResourceAddress | null } | { "AccountBalance": SubstateId } | { "AccountList": ComponentAddress | null } | "SubstatesRead" | "TemplatesRead" | "KeyList" | "TransactionGet" | { "TransactionSend": SubstateId | null } | { "GetNft": [SubstateId | null, ResourceAddress | null] } | "StartWebrtc" | "Admin";