[package]
name = "transaction_submitter"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transaction_generator = { workspace = true }
tari_validator_node_client = { workspace = true }

anyhow = { workspace = true }
# if we set clap version 4 in the workspace it would break other crates
clap = "4.3.21"
tokio = { workspace = true, default-features = true }
