[package]
name = "tari_dan_wallet_storage_sqlite"
authors = ["The Tari Development Community"]
description = "The Tari DAN wallet library"
repository = "https://github.com/tari-project/tari-dan"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_dan_common_types = { path = "../../common_types" }
tari_dan_wallet_sdk = { path = "../sdk" }
tari_engine_types = { path = "../../engine_types" }
tari_template_lib = { path = "../../template_lib" }
tari_transaction = { path = "../../transaction" }
tari_utilities = "0.6"
# Just used for QuorumCertificate
tari_dan_storage = { path = "../../storage" }

serde = "1.0"
serde_json = "1.0"
diesel = { version = "2", features = ["sqlite", "chrono"] }
diesel_migrations = "2"
log = "0.4.17"
chrono = "*"
bigdecimal = "0.4"

# Bundle libsqlite3
libsqlite3-sys = { version = "0.25", features = ["bundled"] }

[dev-dependencies]
tari_dan_common_types = { path = "../../common_types" }

[package.metadata.cargo-machete]
ignored = [
    # We want to bundle this lib
    "libsqlite3-sys",
]
