[package]
name = "tari_consensus"
description = "Tari template runtime engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_crypto = { workspace = true }
tari_ootle_common_types = { workspace = true }
tari_ootle_storage = { workspace = true }
tari_engine_types = { workspace = true }
tari_ootle_transaction = { workspace = true }
tari_epoch_manager = { workspace = true }
tari_state_tree = { workspace = true }
tari_sidechain = { workspace = true }
tari_template_lib_types = { workspace = true }
tari_consensus_types = { workspace = true }
ootle_byte_type = { workspace = true, features = ["crypto"] }

# Used for PublicKey and Signature
tari_common_types = { workspace = true }
tari_shutdown = { workspace = true }

anyhow = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
serde = { workspace = true, default-features = true }
thiserror = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["sync", "time", "macros", "rt"] }

[dev-dependencies]
time = { workspace = true }
