[package]
name = "tari_networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_swarm = { path = "../swarm" }
tari_rpc_framework = { path = "../rpc_framework" }
tari_crypto = "0.19.0"
tari_shutdown = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }

anyhow = "1.0"
async-trait = "0.1.74"
libp2p = { version = "0.53.1", features = ["tokio", "noise", "macros", "ping", "tcp", "identify", "yamux", "relay", "quic", "kad", "dcutr", "gossipsub"] }
log = "0.4.20"
thiserror = "1.0.50"
rand = "0.8"
tokio = { version = "1.34", features = ["macros", "sync"] }