[workspace]
[package]
name = "fees"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_template_lib = { path = "../../../../dan_layer/template_lib" }

[profile.release]
opt-level = 's'     # Optimize for size.
lto = true          # Enable Link Time Optimization.
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic.
strip = "debuginfo" # Strip debug info.

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
tari_dan_engine = { path = "../../../../dan_layer/engine" }
tari_dan_common_types = { path = "../../../../dan_layer/common_types" }

tari_crypto = { workspace = true }
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2", package = "tari_common_types" }
