// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalizeResult } from "../FinalizeResult";
import type { SubstateId } from "../SubstateId";

export interface AccountsCreateResponse {
  address: SubstateId;
  public_key: string;
  result: FinalizeResult;
}
