// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "../Account";

export interface AccountGetResponse {
  account: Account;
  public_key: string;
}
