// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountInfo } from "./AccountInfo";

export interface AccountsListResponse { accounts: Array<AccountInfo>, total: number, }