// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionResult } from "..\\InstructionResult";

export interface AccountsInvokeResponse { result: InstructionResult | null, }