// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AuthLoginRequest { permissions: Array<string>, duration: {secs: number, nanos: number} | null, }