// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { FinalizeResult } from "../FinalizeResult";

export interface ClaimBurnResponse { transaction_id: string, fee: Amount, result: FinalizeResult, }