// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "..\\Amount";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface ClaimBurnRequest { account: ComponentAddressOrName | null, claim_proof: string, max_fee: Amount | null, key_id: number | null, }