// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfidentialOutputStatement } from "../ConfidentialOutputStatement";

export interface ConfidentialCreateOutputProofResponse { proof: ConfidentialOutputStatement, }