// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VaultId } from "..\\VaultId";

export interface ConfidentialViewVaultBalanceRequest {
  vault_id: VaultId;
  minimum_expected_value: number | null;
  maximum_expected_value: number | null;
  view_key_id: number;
}
