// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleId } from "..\\NonFungibleId";

export interface GetAccountNftRequest {
  nft_id: NonFungibleId;
}
