// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "..\\Epoch";

export interface GetValidatorFeesRequest { validator_public_key: string, epoch: Epoch, }