// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBranch } from "./KeyBranch";

export interface KeysCreateRequest {
  branch: KeyBranch;
  specific_index: number | null;
}
