// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonFungibleToken } from "../NonFungibleToken";

export interface ListAccountNftResponse { nfts: Array<NonFungibleToken>, }