// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface ListAccountNftRequest {
  account: ComponentAddressOrName | null;
  limit: number;
  offset: number;
}
