// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "../Amount";
import type { ComponentAddressOrName } from "./ComponentAddressOrName";

export interface MintAccountNftRequest {
  account: ComponentAddressOrName;
  metadata: string;
  mint_fee: Amount | null;
  create_account_nft_fee: Amount | null;
}
