// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletSubstateRecord } from "./WalletSubstateRecord";

export interface SubstatesListResponse {
  substates: Array<WalletSubstateRecord>;
}
