// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateDef } from "../TemplateDef";

export interface TemplatesGetResponse {
  template_definition: TemplateDef;
}
