// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TransactionWaitResultRequest {
  transaction_id: string;
  timeout_secs: number | null;
}
