// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteResult } from "../ExecuteResult";

export interface TransactionSubmitDryRunResponse {
  transaction_id: string;
  result: ExecuteResult;
  json_result: Array<any>;
}
