// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstateAddress } from "../SubstateAddress";

export interface TransactionClaimBurnResponse {
  transaction_id: string;
  inputs: Array<SubstateAddress>;
  outputs: Array<SubstateAddress>;
}
