// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetIdentityResponse {
  peer_id: string;
  public_key: string;
  public_addresses: Array<string>;
}
