// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateDef } from "../TemplateDef";

export interface GetTemplateDefinitionResponse {
  name: string;
  definition: TemplateDef;
}
