// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerConnectionDirection } from "./IndexerConnectionDirection";

export interface IndexerConnection { connection_id: string, peer_id: string, address: string, direction: IndexerConnectionDirection, age: {secs: number, nanos: number}, ping_latency: {secs: number, nanos: number} | null, user_agent: string | null, }