// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateMetadata } from "..\\validator-node-client\\TemplateMetadata";

export interface ListTemplatesResponse {
  templates: Array<TemplateMetadata>;
}
