// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerTransactionFinalizedResult } from "./IndexerTransactionFinalizedResult";

export interface SubmitTransactionResponse {
  transaction_id: string;
  result: IndexerTransactionFinalizedResult;
}
