[package]
name = "tari_scaffolder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_dan_engine = { path = "../../dan_layer/engine"}

clap = "3.2.25"
liquid = "0.26.4"
convert_case  ="0.6.0"
