[package]
name = "tari_rpc_framework"
version = "0.1.0"
edition = "2021"

[dependencies]
tari_shutdown = { git = "https://github.com/sdbondi/tari.git", rev = "e45751090dce2eeac208883fa13865591bdafb46" }
tari_metrics = { git = "https://github.com/sdbondi/tari.git", rev = "e45751090dce2eeac208883fa13865591bdafb46", optional = true }

async-trait = ">=0.1"
bitflags = "2.4"
bytes = "1.5"
futures = "0.3"
log = "0.4"
once_cell = { version = "1.18.0", optional = true }
pin-project = "1.1"
prost = { version = "0.12", features = ["std"] }
thiserror = "1.0"
tokio = { version = "1.34.0", features = ["sync", "time", "rt", "macros"] }
tokio-util = { version = "0.7.10", features = ["compat", "codec"] }
tower = { version = "0.4", features = ["make", "util"] }
tracing = "0.1"

libp2p = "0.53.1"
libp2p-substream = { path = "../libp2p-substream" }

[build-dependencies]
prost-build = "0.12"
proto_builder = { path = "../proto_builder" }

[features]
metrics = ["tari_metrics", "once_cell"]
