[package]
name = "tari_indexer_lib"
description = "Network scanning and indexing library"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_common_types = { workspace = true }
tari_ootle_common_types = { workspace = true }
tari_ootle_storage = { workspace = true }
tari_epoch_manager = { workspace = true }
ootle-network = { workspace = true }
tari_engine_types = { workspace = true }
tari_validator_node_rpc = { workspace = true }

async-trait = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

prometheus-client = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, default-features = false, features = ["rt", "macros", "time"] }

[features]
metrics = ["prometheus-client"]