[package]
name = "tari_template_abi"
description = "Defines the low-level Tari engine ABI for WASM targets"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tari_bor = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["alloc", "derive"] }
hashbrown = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["tari_bor/std"]
# TODO: look into how this is done properly
alloc = ["hashbrown"]
