[package]
name = "tari_template_abi"
version = "0.50.0-pre.0"
edition = "2021"

[dependencies]
tari_bor = { path = "../tari_bor", default-features = false }
serde = { version = "1.0.143", default-features = false, features = ["alloc", "derive"] }
hashbrown = { version = "0.13.2", optional = true }

[features]
default = ["std"]
std = ["tari_bor/std"]
# TODO: look into how this is done properly
alloc = ["hashbrown"]
