[package]
name = "tari_template_abi"
version = "0.0.3"
edition = "2021"
authors = ["The Tari Development Community"]
description = "Defines the low-level Tari engine ABI for WASM targets"
repository = "https://github.com/tari-project/tari-dan"
license = "BSD-3-Clause"

[dependencies]
tari_bor = { path = "../tari_bor", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
hashbrown = { version = "0.13.2", optional = true }

[features]
default = ["std"]
std = ["tari_bor/std"]
# TODO: look into how this is done properly
alloc = ["hashbrown"]
