[package]
name = "tari_template_builtin"
version = "0.50.0-pre.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
tari_engine_types = { path = "../engine_types" }

[build-dependencies]
sha2 = "0.10.6"
