[package]
name = "tari_indexer"
authors = ["The Tari Development Community"]
description = "The Tari DAN indexer implementation"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.35.1"
edition = "2018"

[dependencies]
tari_app_grpc = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_app_grpc" }
tari_app_utilities = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_app_utilities" }
tari_base_node_grpc_client = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_base_node_grpc_client" }
tari_common = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_common" }
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_common_types" }
tari_comms = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_comms" }
tari_comms_logging = { path = "../../comms/tari_comms_logging" }
tari_comms_rpc_macros = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_comms_rpc_macros" }
tari_core = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_core", default-features = false, features = ["transactions"] }
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", tag = "v0.16.6" }
tari_p2p = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_p2p" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_shutdown" }
tari_storage = { git = "https://github.com/tari-project/tari.git", branch = "development", package = "tari_storage" }

tari_dan_app_grpc = { path = "../tari_dan_app_grpc" }
tari_dan_app_utilities = { path = "../tari_dan_app_utilities" }
tari_validator_node_client = { path = "../../clients/validator_node_client" }
tari_dan_common_types = { path = "../../dan_layer/common_types" }
tari_dan_core = { path = "../../dan_layer/core" }
tari_dan_engine = { path = "../../dan_layer/engine" }
tari_dan_storage = { path = "../../dan_layer/storage" }
tari_dan_storage_sqlite = { path = "../../dan_layer/storage_sqlite" }
tari_engine_types = { path = "../../dan_layer/engine_types" }
tari_template_lib = { path = "../../dan_layer/template_lib" }
tari_transaction = { path = "../../dan_layer/transaction" }
tari_validator_node = { path = "../tari_validator_node" }

anyhow = "1.0.53"
async-trait = "0.1.50"
axum = "0.6.0"
axum-jrpc = { version = "0.3.2", features = ["anyhow_error"] }
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive", "env"] }
config = "0.13.0"
diesel = { version = "2", default-features = false, features = ["sqlite", "chrono"] }
diesel_migrations = "2"
futures = { version = "^0.3.1" }
lmdb-zero = "0.4.4"
log = { version = "0.4.8", features = ["std"] }
prost = "0.9"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "^1.0.20"
tokio = { version = "1.10", features = ["macros", "time", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1.7", features = ["sync"] }
tonic = "0.6.2"
tower = "0.4"
tower-layer = "0.3"
tower-http = { version = "0.3.0", features = ["cors"] }