[package]
name = "tari_validator_node_cli"
authors = ["The Tari Development Community"]
description = "The Tari validator node CLI"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.35.1"
edition = "2018"

[dependencies]
tari_utilities = { git = "https://github.com/tari-project/tari_utilities.git", tag = "v0.4.7" }
tari_dan_engine = { path = "../../dan_layer/engine"}
tari_dan_common_types = { path = "../../dan_layer/common_types"}
tari_engine_types = {path = "../../dan_layer/engine_types"}

anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive"] }
log = "0.4.17"
multiaddr = "0.14.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.36"
tokio = { version = "1", features = ["macros"] }
