---
name: Source Coverage

'on':
  workflow_dispatch:

env:
  toolchain: nightly-2022-05-01

jobs:
  coverage:
    name: test and generate cov
    runs-on: [ self-hosted, ubuntu18.04-high-mem ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ubuntu dependencies
        run: |
          sudo apt-get update
          sudo bash scripts/install_ubuntu_dependencies.sh

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - name: cargo test compile
        env:
          RUSTFLAGS: "-C instrument-coverage"
          RUSTDOCFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "coverage_data-%p-%m.profraw"
        run: cargo test --all-features --no-fail-fast

      - id: coverage
        name: Prepare coverage data
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          cargo install grcov
          grcov . -s . --binary-path ./target/debug -t coveralls --branch --ignore-not-existing \
             -o ./target/coveralls_coverage.json \
             --token $COVERALLS_REPO_TOKEN \
             --ignore target/**/*.rs \
             --ignore **/.cargo/**/*.rs \
             --vcs-branch $GITHUB_REF_NAME \
             --service-name github \
             --service-job-id ${GITHUB_RUN_ID}

      - name: archive-coverage
        id: archive-coverage
        uses: actions/upload-artifact@v3
        with:
          path: target/coveralls_coverage.json
          name: coveralls-coverage

      - name: Coveralls upload
        uses: toshke/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/coveralls_coverage.json
          file-format: coveralls
